spring:
  data:
    solr:
      host: http://192.168.13.129:8888/solr
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/ygx-v9?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=UTC&allowMultiQueries=true
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 123456
  rabbitmq:
    host: 192.168.13.129
    port: 5672
    password: 123
    username: ygx
    virtual-host: /ygx

dubbo:
  application:
    name: search-service
  registry:
    protocol: zookeeper
    address: 192.168.13.129:2181
  protocol:
    port: 28802
server:
  port: 8081

