dubbo:
  application:
    name: background
  registry:
    protocol: zookeeper
    address: 192.168.13.129:2181
server:
  port: 9090

spring:
  rabbitmq:
    host: 192.168.13.129
    port: 5672
    password: 123
    username: ygx
    virtual-host: /ygx
  thymeleaf:
    cache: false

fdfs:
  so-timeout: 1500
  connect-timeout: 600
  pool:
    jmx-enabled: false
  thumb-image:
    width: 100
    height: 100
  tracker-list: 192.168.13.129:22122

image:
  server: http://192.168.13.129/
