spring:
  rabbitmq:
    host: 192.168.13.129
    port: 5672
    password: 123
    username: ygx
    virtual-host: /ygx
    publisher-confirm-type: correlated
    publisher-returns: true
    template:
      mandatory: true
